const $=id=>document.getElementById(id);const download=(b,n)=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};const loadImage=f=>new Promise((res,rej)=>{if(!f)return rej(Error('Please choose an image.'));const i=new Image;i.onload=()=>res(i);i.onerror=()=>rej(Error('Could not read this image.'));i.src=URL.createObjectURL(f)});const blob=(c,t,q)=>new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('Format not supported')),t,q));const canvas=async(f,w,h)=>{const i=await loadImage(f),c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));c.getContext('2d').drawImage(i,0,0,c.width,c.height);return c};const ext=t=>t==='image/png'?'png':t==='image/webp'?'webp':'jpg';
$('quality').oninput=e=>$('qualityValue').textContent=e.target.value;
$('compressBtn').onclick=async()=>{try{const f=$('compressFile').files[0];const i=await loadImage(f),c=await canvas(f,i.naturalWidth,i.naturalHeight),t=$('compressFormat').value,b=await blob(c,t,Number($('quality').value)/100);download(b,'compressed-'+f.name.replace(/\.[^.]+$/,'')+'.'+ext(t));$('compressResult').textContent=`Done: ${(f.size/1024).toFixed(1)} KB → ${(b.size/1024).toFixed(1)} KB`}catch(e){$('compressResult').textContent=e.message}};
$('resizeBtn').onclick=async()=>{try{const f=$('resizeFile').files[0],i=await loadImage(f);let w=Number($('resizeW').value),h=Number($('resizeH').value);if(!w&&!h)throw Error('Enter width or height.');if($('keepRatio').checked){if(w&&!h)h=Math.round(i.naturalHeight*w/i.naturalWidth);else if(h&&!w)w=Math.round(i.naturalWidth*h/i.naturalHeight)}w=w||i.naturalWidth;h=h||i.naturalHeight;const b=await blob(await canvas(f,w,h),'image/png');download(b,'resized-'+f.name.replace(/\.[^.]+$/,'')+'.png');$('resizeResult').textContent=`Done: ${w} × ${h}`}catch(e){$('resizeResult').textContent=e.message}};
$('convertBtn').onclick=async()=>{try{const f=$('convertFile').files[0],i=await loadImage(f),c=await canvas(f,i.naturalWidth,i.naturalHeight),t=$('convertFormat').value,b=await blob(c,t,.92);download(b,'converted-'+f.name.replace(/\.[^.]+$/,'')+'.'+ext(t));$('convertResult').textContent='Converted successfully.'}catch(e){$('convertResult').textContent=e.message}};
$('cropBtn').onclick=async()=>{try{const f=$('cropFile').files[0],i=await loadImage(f),r=Number($('cropRatio').value);let w=i.naturalWidth,h=Math.round(w/r);if(h>i.naturalHeight){h=i.naturalHeight;w=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(i,(i.naturalWidth-w)/2,(i.naturalHeight-h)/2,w,h,0,0,w,h);const b=await blob(c,'image/jpeg',.92);download(b,'cropped-'+f.name.replace(/\.[^.]+$/,'')+'.jpg');$('cropResult').textContent=`Cropped to ${w} × ${h}`}catch(e){$('cropResult').textContent=e.message}};
function esc(s){return s.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}async function imageJpeg(f,maxW,maxH){const i=await loadImage(f),scale=Math.min(1,maxW/i.naturalWidth,maxH/i.naturalHeight),w=Math.max(1,Math.round(i.naturalWidth*scale)),h=Math.max(1,Math.round(i.naturalHeight*scale)),c=await canvas(f,w,h),b=await blob(c,'image/jpeg',.9);return{buf:new Uint8Array(await b.arrayBuffer()),w,h}}async function makePDF(files,size){const pw=size==='a4'?595:612,ph=size==='a4'?842:792,objs=[],kids=[];const add=x=>{objs.push(x);return objs.length};const cat=add(''),pages=add('');for(const f of files){const im=await imageJpeg(f,pw-40,ph-40);let bin='';for(let i=0;i<im.buf.length;i+=32768)bin+=String.fromCharCode(...im.buf.subarray(i,i+32768));const io=add(`<< /Type /XObject /Subtype /Image /Width ${im.w} /Height ${im.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${im.buf.length} >>\nstream\n${bin}\nendstream`);const x=20+(pw-40-im.w)/2,y=20+(ph-40-im.h)/2,content=`q\n${im.w} 0 0 ${im.h} ${x} ${y} cm\n/Im1 Do\nQ`,co=add(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`),po=add(`<< /Type /Page /Parent ${pages} 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im1 ${io} 0 R >> >> /Contents ${co} 0 R >>`);kids.push(po)}objs[cat-1]=`<< /Type /Catalog /Pages ${pages} 0 R >>`;objs[pages-1]=`<< /Type /Pages /Kids [${kids.map(x=>x+' 0 R').join(' ')}] /Count ${kids.length} >>`;let pdf='%PDF-1.4\n',off=[0];for(let i=0;i<objs.length;i++){off[i+1]=pdf.length;pdf+=`${i+1} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)pdf+=String(off[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root ${cat} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
$('pdfBtn').onclick=async()=>{try{const fs=[...$('pdfFiles').files];if(!fs.length)throw Error('Choose one or more images.');const b=await makePDF(fs,$('pdfSize').value);download(b,'images.pdf');$('pdfResult').textContent=`PDF created with ${fs.length} image(s).`}catch(e){$('pdfResult').textContent='Could not create PDF: '+e.message}};
$('search').oninput=e=>{const q=e.target.value.toLowerCase().trim();document.querySelectorAll('.tool').forEach(x=>x.style.display=x.dataset.name.includes(q)?'':'none')};$('menuBtn').onclick=()=>$('nav').classList.toggle('open');$('year').textContent=new Date().getFullYear();

